import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print(array.ndim)
print(array.size)
print(len(array))
print(array.shape)
print(array.dtype)
print(array.itemsize )
print(array.nbytes)
